### ISSUE TITLE
build pkg-config error on mac m1

### ISSUE THREAD

**Issue by thedrugsdontwork** [rdkit/rdkit-build-helpers#1]
Hi all, when i run build.sh  appear this error .
Anything can i do? 
Thanks!
TASK [build pkg-config] 
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "make -j6 clean && make -j6 && make -j6 install", "delta": "0:00:02.385933", "end": "2023-01-09 16:26:08.573416", "msg": "non-zero return code", "rc": 2, "start": "2023-01-09 16:26:06.187483", "stderr": "gatomic.c:392:10: warning: incompatible integer to pointer conversion passing 'gssize' (aka 'long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]\n  return g_atomic_pointer_add ((volatile gpointer *) atomic, val);\n         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n./gatomic.h:170:46: note: expanded from macro 'g_atomic_pointer_add'\n    (gssize) __sync_fetch_and_add ((atomic), (val));                         \\\n                                             ^~~~~\ngatomic.c:416:10: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]\n  return g_atomic_pointer_and ((volatile gpointer *) atomic, val);\n         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n./gatomic.h:177:45: note: expanded from macro 'g_atomic_pointer_and'\n    (gsize) __sync_fetch_and_and ((atomic), (val));                          \\\n                                            ^~~~~\ngatomic.c:440:10: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]\n  return g_atomic_pointer_or ((volatile gpointer *) atomic, val);\n         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n./gatomic.h:184:44: note: expanded from macro 'g_atomic_pointer_or'\n    (gsize) __sync_fetch_and_or ((atomic), (val));                           \\\n                                           ^~~~~\ngatomic.c:464:10: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]\n  return g_atomic_pointer_xor ((volatile gpointer *) atomic, val);\n         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n./gatomic.h:191:45: note: expanded from macro 'g_atomic_pointer_xor'\n    (gsize) __sync_fetch_and_xor ((atomic), (val));                          \\\n                                            ^~~~~\n4 warnings generated.\ngdataset.c:1191:3: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'GData *' (aka 'struct _GData *') [-Wint-conversion]\n  g_atomic_pointer_or (datalist, (gsize)flags);\n  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n../glib/gatomic.h:184:44: note: expanded from macro 'g_atomic_pointer_or'\n    (gsize) __sync_fetch_and_or ((atomic), (val));                           \\\n                                           ^~~~~\ngdataset.c:1214:3: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'GData *' (aka 'struct _GData *') [-Wint-conversion]\n  g_atomic_pointer_and (datalist, ~(gsize)flags);\n  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n../glib/gatomic.h:177:45: note: expanded from macro 'g_atomic_pointer_and'\n    (gsize) __sync_fetch_and_and ((atomic), (val));                          \\\n                                            ^~~~~\n2 warnings generated.\ngfileutils.c:1079:14: error: implicit declaration of function 'fallocate' is invalid in C99 [-Werror,-Wimplicit-function-declaration]\n      (void) fallocate (fd, 0, 0, length);\n             ^\ngfileutils.c:1079:14: note: did you mean 'alloca'?\n/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/alloca.h:32:7: note: 'alloca' declared here\nvoid    *alloca(size_t);                /* built-in for gcc */\n         ^\n1 error generated.\nmake[6]: *** [libglib_2_0_la-gfileutils.lo] Error 1\nmake[6]: *** Waiting for unfinished jobs....\nggettext.c:109:23: warning: expression result unused [-Wunused-value]\n      bindtextdomain (GETTEXT_PACKAGE, GLIB_LOCALE_DIR);\n                      ^~~~~~~~~~~~~~~\n../config.h:34:25: note: expanded from macro 'GETTEXT_PACKAGE'\n#define GETTEXT_PACKAGE \"glib20\"\n                        ^~~~~~~~\n./glibintl.h:37:43: note: expanded from macro 'bindtextdomain'\n#define bindtextdomain(Domain,Directory) (Domain) \n                                          ^~~~~~\n1 warning generated.\nmake[5]: *** [all-recursive] Error 1\nmake[4]: *** [all] Error 2\nmake[3]: *** [all-recursive] Error 1\nmake[2]: *** [all] Error 2\nmake[1]: *** [all-recursive] Error 1\nmake: *** [all] Error 2", "stderr_lines": ["gatomic.c:392:10: warning: incompatible integer to pointer conversion passing 'gssize' (aka 'long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]", "  return g_atomic_pointer_add ((volatile gpointer *) atomic, val);", "         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "./gatomic.h:170:46: note: expanded from macro 'g_atomic_pointer_add'", "    (gssize) __sync_fetch_and_add ((atomic), (val));                         \\", "                                             ^~~~~", "gatomic.c:416:10: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]", "  return g_atomic_pointer_and ((volatile gpointer *) atomic, val);", "         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "./gatomic.h:177:45: note: expanded from macro 'g_atomic_pointer_and'", "    (gsize) __sync_fetch_and_and ((atomic), (val));                          \\", "                                            ^~~~~", "gatomic.c:440:10: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]", "  return g_atomic_pointer_or ((volatile gpointer *) atomic, val);", "         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "./gatomic.h:184:44: note: expanded from macro 'g_atomic_pointer_or'", "    (gsize) __sync_fetch_and_or ((atomic), (val));                           \\", "                                           ^~~~~", "gatomic.c:464:10: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'gpointer' (aka 'void *') [-Wint-conversion]", "  return g_atomic_pointer_xor ((volatile gpointer *) atomic, val);", "         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "./gatomic.h:191:45: note: expanded from macro 'g_atomic_pointer_xor'", "    (gsize) __sync_fetch_and_xor ((atomic), (val));                          \\", "                                            ^~~~~", "4 warnings generated.", "gdataset.c:1191:3: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'GData *' (aka 'struct _GData *') [-Wint-conversion]", "  g_atomic_pointer_or (datalist, (gsize)flags);", "  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "../glib/gatomic.h:184:44: note: expanded from macro 'g_atomic_pointer_or'", "    (gsize) __sync_fetch_and_or ((atomic), (val));                           \\", "                                           ^~~~~", "gdataset.c:1214:3: warning: incompatible integer to pointer conversion passing 'gsize' (aka 'unsigned long') to parameter of type 'GData *' (aka 'struct _GData *') [-Wint-conversion]", "  g_atomic_pointer_and (datalist, ~(gsize)flags);", "  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "../glib/gatomic.h:177:45: note: expanded from macro 'g_atomic_pointer_and'", "    (gsize) __sync_fetch_and_and ((atomic), (val));                          \\", "                                            ^~~~~", "2 warnings generated.", "gfileutils.c:1079:14: error: implicit declaration of function 'fallocate' is invalid in C99 [-Werror,-Wimplicit-function-declaration]", "      (void) fallocate (fd, 0, 0, length);", "             ^", "gfileutils.c:1079:14: note: did you mean 'alloca'?", "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/alloca.h:32:7: note: 'alloca' declared here", "void    *alloca(size_t);                /* built-in for gcc */", "         ^", "1 error generated.", "make[6]: *** [libglib_2_0_la-gfileutils.lo] Error 1", "make[6]: *** Waiting for unfinished jobs....", "ggettext.c:109:23: warning: expression result unused [-Wunused-value]", "      bindtextdomain (GETTEXT_PACKAGE, GLIB_LOCALE_DIR);", "                      ^~~~~~~~~~~~~~~", "../config.h:34:25: note: expanded from macro 'GETTEXT_PACKAGE'", "#define GETTEXT_PACKAGE \"glib20\"", "                        ^~~~~~~~", "./glibintl.h:37:43: note: expanded from macro 'bindtextdomain'", "#define bindtextdomain(Domain,Directory) (Domain) ", "                                          ^~~~~~", "1 warning generated.", "make[5]: *** [all-recursive] Error 1", "make[4]: *** [all] Error 2", "make[3]: *** [all-recursive] Error 1", "make[2]: *** [all] Error 2", "make[1]: *** [all-recursive] Error 1", "make: *** [all] Error 2"], "stdout": "Making clean in glib\nMaking clean in .\ntest -z \"  \" || rm -f   \ntest -z \"*.log *.trs \" || rm -f *.log *.trs \ntest -z \"\" || rm -f \nrm -rf .libs _libs\ntest -z \"\" || rm -f \ntest -z \"\" || rm -f \nrm -f *.lo\ntest -z \"\" || rm -f \ntest -z \"test-suite.log\" || rm -f test-suite.log\nMaking clean in m4macros\ntest -z \"  \" || rm -f   \ntest -z \"*.log *.trs \" || rm -f *.log *.trs \ntest -z \"\" || rm -f \nrm -rf .libs _libs\ntest -z \"\" || rm -f \ntest -z \"\" || rm -f \nrm -f *.lo\ntest -z \"\" || rm -f \ntest -z \"test-suite.log\" || rm -f test-suite.log\nMaking clean in glib\nMaking clean in libcharset\ntest -z \"  \" || rm -f   \ntest -z \"*.log *.trs  charset.alias ref-add.sed ref-del.sed\" || rm -f *.log *.trs  charset.alias ref-add.sed ref-del.sed\ntest -z \"\" || rm -f \nrm -rf .libs _libs\ntest -z \" libcharset.la\" || rm -f  libcharset.la\nrm -f *.o\ntest -z \"\" || rm -f \nrm -f *.lo\ntest -z \"\" || rm -f \ntest -z \"test-suite.log\" || rm -f test-suite.log\nrm -f ./so_locations\nMaking clean in gnulib\ntest -z \"  \" || rm -f   \ntest -z \"*.log *.trs \" || rm -f *.log *.trs \ntest -z \"\" || rm -f \nrm -rf .libs _libs\ntest -z \" libgnulib.la\" || rm -f  libgnulib.la\nrm -f *.o\ntest -z \"\" || rm -f \nrm -f *.lo\ntest -z \"\" || rm -f \ntest -z \"test-suite.log\" || rm -f test-suite.log\nrm -f ./so_locations\nMaking clean in .\ntest -z \"  \" || rm -f   \ntest -z \"*.log *.trs  glib-public-headers.txt\" || rm -f *.log *.trs  glib-public-headers.txt\ntest -z \"\" || rm -f \nrm -rf .libs _libs\ntest -z \" libglib-2.0.la\" || rm -f  libglib-2.0.la\nrm -f *.o\ntest -z \"\" || rm -f \nrm -f *.lo\ntest -z \"\" || rm -f \ntest -z \"test-suite.log\" || rm -f test-suite.log\nrm -f ./so_locations\nMaking clean in .\ntest -z \"*.gcda *.gcno *.gcov\" || rm -f *.gcda *.gcno *.gcov\nrm -rf .libs _libs\nrm -f *.o\n rm -f pkg-config\nrm -f *.lo\nMaking clean in check\nrm -rf .libs _libs\nrm -f *.lo\n/Library/Developer/CommandLineTools/usr/bin/make  all-recursive\nMaking all in glib\n/Library/Developer/CommandLineTools/usr/bin/make  all-recursive\nMaking all in .\nMaking all in m4macros\n/Library/Developer/CommandLineTools/usr/bin/make  all-am\nmake[5]: Nothing to be done for `all-am'.\nMaking all in glib\n  GEN      glibconfig-stamp\nconfig.status: executing glib/glibconfig.h commands\nconfig.status: glib/glibconfig.h is unchanged\n/Library/Developer/CommandLineTools/usr/bin/make  all-recursive\nMaking all in libcharset\n/Library/Developer/CommandLineTools/usr/bin/make  all-am\n  GEN      ref-add.sed\n  GEN      ref-del.sed\n  CC       libcharset_la-localcharset.lo\n  GEN      charset.alias\n  CCLD     libcharset.la\nMaking all in gnulib\n/Library/Developer/CommandLineTools/usr/bin/make  all-am\n  CC       libgnulib_la-asnprintf.lo\n  CC       libgnulib_la-printf-parse.lo\n  CC       libgnulib_la-printf-args.lo\n  CC       libgnulib_la-vasnprintf.lo\n  CC       libgnulib_la-printf.lo\n  CCLD     libgnulib.la\nMaking all in .\n  CC       libglib_2_0_la-gallocator.lo\n  CC       libglib_2_0_la-gcache.lo\n  CC       libglib_2_0_la-gcompletion.lo\n  CC       libglib_2_0_la-grel.lo\n  CC       libglib_2_0_la-gthread-deprecated.lo\n  CC       libglib_2_0_la-garray.lo\n  CC       libglib_2_0_la-gasyncqueue.lo\n  CC       libglib_2_0_la-gatomic.lo\n  CC       libglib_2_0_la-gbacktrace.lo\n  CC       libglib_2_0_la-gbase64.lo\n  CC       libglib_2_0_la-gbitlock.lo\n  CC       libglib_2_0_la-gbookmarkfile.lo\n  CC       libglib_2_0_la-gbytes.lo\n  CC       libglib_2_0_la-gcharset.lo\n  CC       libglib_2_0_la-gchecksum.lo\n  CC       libglib_2_0_la-gconvert.lo\n  CC       libglib_2_0_la-gdataset.lo\n  CC       libglib_2_0_la-gdate.lo\n  CC       libglib_2_0_la-gdatetime.lo\n  CC       libglib_2_0_la-gdir.lo\n  CC       libglib_2_0_la-genviron.lo\n  CC       libglib_2_0_la-gerror.lo\n  CC       libglib_2_0_la-gfileutils.lo\n  CC       libglib_2_0_la-ggettext.lo\n  CC       libglib_2_0_la-ghash.lo\n  CC       libglib_2_0_la-ghmac.lo\n  CC       libglib_2_0_la-ghook.lo\n  CC       libglib_2_0_la-ghostutils.lo", "stdout_lines": ["Making clean in glib", "Making clean in .", "test -z \"  \" || rm -f   ", "test -z \"*.log *.trs \" || rm -f *.log *.trs ", "test -z \"\" || rm -f ", "rm -rf .libs _libs", "test -z \"\" || rm -f ", "test -z \"\" || rm -f ", "rm -f *.lo", "test -z \"\" || rm -f ", "test -z \"test-suite.log\" || rm -f test-suite.log", "Making clean in m4macros", "test -z \"  \" || rm -f   ", "test -z \"*.log *.trs \" || rm -f *.log *.trs ", "test -z \"\" || rm -f ", "rm -rf .libs _libs", "test -z \"\" || rm -f ", "test -z \"\" || rm -f ", "rm -f *.lo", "test -z \"\" || rm -f ", "test -z \"test-suite.log\" || rm -f test-suite.log", "Making clean in glib", "Making clean in libcharset", "test -z \"  \" || rm -f   ", "test -z \"*.log *.trs  charset.alias ref-add.sed ref-del.sed\" || rm -f *.log *.trs  charset.alias ref-add.sed ref-del.sed", "test -z \"\" || rm -f ", "rm -rf .libs _libs", "test -z \" libcharset.la\" || rm -f  libcharset.la", "rm -f *.o", "test -z \"\" || rm -f ", "rm -f *.lo", "test -z \"\" || rm -f ", "test -z \"test-suite.log\" || rm -f test-suite.log", "rm -f ./so_locations", "Making clean in gnulib", "test -z \"  \" || rm -f   ", "test -z \"*.log *.trs \" || rm -f *.log *.trs ", "test -z \"\" || rm -f ", "rm -rf .libs _libs", "test -z \" libgnulib.la\" || rm -f  libgnulib.la", "rm -f *.o", "test -z \"\" || rm -f ", "rm -f *.lo", "test -z \"\" || rm -f ", "test -z \"test-suite.log\" || rm -f test-suite.log", "rm -f ./so_locations", "Making clean in .", "test -z \"  \" || rm -f   ", "test -z \"*.log *.trs  glib-public-headers.txt\" || rm -f *.log *.trs  glib-public-headers.txt", "test -z \"\" || rm -f ", "rm -rf .libs _libs", "test -z \" libglib-2.0.la\" || rm -f  libglib-2.0.la", "rm -f *.o", "test -z \"\" || rm -f ", "rm -f *.lo", "test -z \"\" || rm -f ", "test -z \"test-suite.log\" || rm -f test-suite.log", "rm -f ./so_locations", "Making clean in .", "test -z \"*.gcda *.gcno *.gcov\" || rm -f *.gcda *.gcno *.gcov", "rm -rf .libs _libs", "rm -f *.o", " rm -f pkg-config", "rm -f *.lo", "Making clean in check", "rm -rf .libs _libs", "rm -f *.lo", "/Library/Developer/CommandLineTools/usr/bin/make  all-recursive", "Making all in glib", "/Library/Developer/CommandLineTools/usr/bin/make  all-recursive", "Making all in .", "Making all in m4macros", "/Library/Developer/CommandLineTools/usr/bin/make  all-am", "make[5]: Nothing to be done for `all-am'.", "Making all in glib", "  GEN      glibconfig-stamp", "config.status: executing glib/glibconfig.h commands", "config.status: glib/glibconfig.h is unchanged", "/Library/Developer/CommandLineTools/usr/bin/make  all-recursive", "Making all in libcharset", "/Library/Developer/CommandLineTools/usr/bin/make  all-am", "  GEN      ref-add.sed", "  GEN      ref-del.sed", "  CC       libcharset_la-localcharset.lo", "  GEN      charset.alias", "  CCLD     libcharset.la", "Making all in gnulib", "/Library/Developer/CommandLineTools/usr/bin/make  all-am", "  CC       libgnulib_la-asnprintf.lo", "  CC       libgnulib_la-printf-parse.lo", "  CC       libgnulib_la-printf-args.lo", "  CC       libgnulib_la-vasnprintf.lo", "  CC       libgnulib_la-printf.lo", "  CCLD     libgnulib.la", "Making all in .", "  CC       libglib_2_0_la-gallocator.lo", "  CC       libglib_2_0_la-gcache.lo", "  CC       libglib_2_0_la-gcompletion.lo", "  CC       libglib_2_0_la-grel.lo", "  CC       libglib_2_0_la-gthread-deprecated.lo", "  CC       libglib_2_0_la-garray.lo", "  CC       libglib_2_0_la-gasyncqueue.lo", "  CC       libglib_2_0_la-gatomic.lo", "  CC       libglib_2_0_la-gbacktrace.lo", "  CC       libglib_2_0_la-gbase64.lo", "  CC       libglib_2_0_la-gbitlock.lo", "  CC       libglib_2_0_la-gbookmarkfile.lo", "  CC       libglib_2_0_la-gbytes.lo", "  CC       libglib_2_0_la-gcharset.lo", "  CC       libglib_2_0_la-gchecksum.lo", "  CC       libglib_2_0_la-gconvert.lo", "  CC       libglib_2_0_la-gdataset.lo", "  CC       libglib_2_0_la-gdate.lo", "  CC       libglib_2_0_la-gdatetime.lo", "  CC       libglib_2_0_la-gdir.lo", "  CC       libglib_2_0_la-genviron.lo", "  CC       libglib_2_0_la-gerror.lo", "  CC       libglib_2_0_la-gfileutils.lo", "  CC       libglib_2_0_la-ggettext.lo", "  CC       libglib_2_0_la-ghash.lo", "  CC       libglib_2_0_la-ghmac.lo", "  CC       libglib_2_0_la-ghook.lo", "  CC       libglib_2_0_la-ghostutils.lo"]}

**Comment by ptosco** [comment]
@thedrugsdontwork The recipe works for me, and I have a Mac M1. You need to `cd` into the `arm64` directory and then run
```
../build.sh
```
from there.
Also, make sure you have a complete and up-to-date Xcode package.

**Comment by thedrugsdontwork** [comment]
thanks for your advice.
